lib/live_qchatex_web/router.ex
defmodule LiveQchatexWeb.Router do
  use LiveQchatexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :put_layout, {LiveQchatexWeb.LayoutView, :app}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LiveQchatexWeb.Plug.SessionSetup
  end

  scope "/", LiveQchatexWeb do
    pipe_through :browser

    live "/", LiveChat.Home, session: [:sid]
    live "/chat/:id", LiveChat.Chat, session: [:sid]
    live "/user/:id", LiveChat.User, session: [:sid]
  end
end

lib/live_qchatex_web/views/layout_view.ex
defmodule LiveQchatexWeb.LayoutView do
  use LiveQchatexWeb, :view

  def render_counters(assigns), do: render("counters.html", assigns)
  def render_disclaimer(assigns), do: render("disclaimer.html", assigns)
  def render_invites(assigns), do: render("invites.html", assigns)

  def render_version(),
    do: "Live Qchatex <b>v#{get_app_version()}.#{get_commit_date()}</b> at #{get_commit_link()}"

  def repo_url(path \\ ""),
    do: Application.get_env(:live_qchatex, LiveQchatexWeb.Endpoint)[:repo] <> path

  def demo_url(path \\ ""),
    do: Application.get_env(:live_qchatex, LiveQchatexWeb.Endpoint)[:demo] <> path

  def timer_clean_chats(), do: :cron_interval_clean_chats |> get_timer()
  def timer_clean_users(), do: :cron_interval_clean_users |> get_timer()

  defp get_timer(key), do: Integer.floor_div(Application.get_env(:live_qchatex, :timers)[key], 60)

  defp get_app_version(), do: Application.spec(:live_qchatex, :vsn)
  defp get_commit_sha(), do: LiveQchatex.Application.version(:hash)
  defp get_commit_date(), do: LiveQchatex.Application.version(:date)

  defp get_commit_link() do
    commit_sha = get_commit_sha()
    path = "/commit/#{commit_sha}"

    "<a href=\"#{repo_url(path)}\" target=\"_blank\">##{commit_sha}</a>"
  end
end

lib/live_qchatex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Live Qchatex · Elixir + Phoenix LiveView + PubSub + Presence + Mnesia + Memento + Cluster · Fiqus.coop</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="<%= Routes.live_path(@conn, LiveQchatexWeb.LiveChat.Home) %>">Home</a></li>
            <li><a href="<%= repo_url() %>" target="_blank">Repo</a></li>
            <li><a href="<%= demo_url("/lqchatex-overview.pdf") %>" target="_blank">Overview PDF</a></li>
            <%= if !LiveQchatex.Application.env?(:prod) do %>
            <li><a href="<%= demo_url() %>" target="_blank">Live Demo</a></li>
            <% end %>
          </ul>
        </nav>
        <h1>Live Qchatex</h1>
        <a href="<%= Routes.live_path(@conn, LiveQchatexWeb.LiveChat.Home) %>" class="main-logo">
          <img src="<%= Routes.static_path(@conn, "/images/fiqus-logo.png") %>" alt="Fiqus Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= raw get_flash(@conn, :info) %></p>
      <p class="alert alert-success" role="alert"><%= raw get_flash(@conn, :success) %></p>
      <p class="alert alert-danger" role="alert"><%= raw get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer><%= raw render_version() %></footer>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/live_qchatex_web/templates/layout/counters.html.eex
<section class="row">
  <article class="column">
      <h2>Current living chats: <%= @counters.chats%></h2>
  </article>
  <article class="column">
      <h2>Current living users: <%= @counters.users%></h2>
  </article>
</section>

lib/live_qchatex_web/templates/layout/disclaimer.html.eex
<section class="disclaimer">
  <div><b>NOTE:</b> All chats, messages and users will be automatically deleted!</div>
  <div>Empty chat rooms and all its messages after <b><%= timer_clean_chats() %></b> minutes without having members.</div>
  <div>Users will be purged after <b><%= timer_clean_users() %></b> minutes of quitting the app.</div>
</section>

lib/live_qchatex_web/templates/layout/invites.html.eex
<%= if length(@invites) > 0 do %>
<section class="user-chats-invites">
  <h2>Private chat invites</h2>
  <ul>
    <%= for invite <- @invites do %> 
    <li><%= link(invite.from,
      to: Routes.live_path(@socket, LiveQchatexWeb.LiveChat.Chat, invite.chat),
      target: "_blank",
      title: "Click to join this private chat!") %></li>
    <% end %>
  </ul>
</section>
<% end %>